[Greenshift]
name = "Greenshift"
min_pop = 0
advisory_report = "Advisory Level: <b>Green Star</b></center><BR>Your sector's advisory level is Green Star. Surveillance information shows no credible threats to Nanotrasen assets within the Spinward Sector at this time. As always, the Department advises maintaining vigilance against potential threats, regardless of a lack of known threats."
ruleset_ranges.roundstart.low = 0
ruleset_ranges.roundstart.high = 0
ruleset_ranges.roundstart.half_range_pop_threshold = 25
ruleset_ranges.roundstart.full_range_pop_threshold = 50
ruleset_ranges.light_midround.low = 0
ruleset_ranges.light_midround.high = 0
ruleset_ranges.light_midround.half_range_pop_threshold = 25
ruleset_ranges.light_midround.full_range_pop_threshold = 40
ruleset_ranges.light_midround.time_threshold = 18000
ruleset_ranges.heavy_midround.low = 0
ruleset_ranges.heavy_midround.high = 0
ruleset_ranges.heavy_midround.half_range_pop_threshold = 25
ruleset_ranges.heavy_midround.full_range_pop_threshold = 40
ruleset_ranges.heavy_midround.time_threshold = 36000
ruleset_ranges.latejoin.low = 0
ruleset_ranges.latejoin.high = 0
ruleset_ranges.latejoin.half_range_pop_threshold = 25
ruleset_ranges.latejoin.full_range_pop_threshold = 40
ruleset_ranges.latejoin.time_threshold = 0

[Low Chaos]
name = "Low Chaos"
min_pop = 0
advisory_report = "Advisory Level: <b>Yellow Star</b></center><BR>Your sector's advisory level is Yellow Star. Surveillance shows a credible risk of enemy attack against our assets in the Spinward Sector. We advise a heightened level of security alongside maintaining vigilance against potential threats."
ruleset_ranges.roundstart.low = 1
ruleset_ranges.roundstart.high = 1
ruleset_ranges.roundstart.half_range_pop_threshold = 25
ruleset_ranges.roundstart.full_range_pop_threshold = 40
ruleset_ranges.light_midround.low = 1
ruleset_ranges.light_midround.high = 2
ruleset_ranges.light_midround.half_range_pop_threshold = 25
ruleset_ranges.light_midround.full_range_pop_threshold = 40
ruleset_ranges.light_midround.time_threshold = 18000
ruleset_ranges.heavy_midround.low = 0
ruleset_ranges.heavy_midround.high = 1
ruleset_ranges.heavy_midround.half_range_pop_threshold = 25
ruleset_ranges.heavy_midround.full_range_pop_threshold = 40
ruleset_ranges.heavy_midround.time_threshold = 36000
ruleset_ranges.latejoin.low = 0
ruleset_ranges.latejoin.high = 1
ruleset_ranges.latejoin.half_range_pop_threshold = 25
ruleset_ranges.latejoin.full_range_pop_threshold = 40
ruleset_ranges.latejoin.time_threshold = 0

[Low-Medium Chaos]
name = "Low-Medium Chaos"
min_pop = 0
advisory_report = "Advisory Level: <b>Red Star</b></center><BR>Your sector's advisory level is Red Star. The Department of Intelligence has decrypted Cybersun communications suggesting a high likelihood of attacks on Nanotrasen assets within the Spinward Sector. Stations in the region are advised to remain highly vigilant for signs of enemy activity and to be on high alert."
ruleset_ranges.roundstart.low = 1
ruleset_ranges.roundstart.high = 2
ruleset_ranges.roundstart.half_range_pop_threshold = 25
ruleset_ranges.roundstart.full_range_pop_threshold = 40
ruleset_ranges.light_midround.low = 1
ruleset_ranges.light_midround.high = 2
ruleset_ranges.light_midround.half_range_pop_threshold = 25
ruleset_ranges.light_midround.full_range_pop_threshold = 40
ruleset_ranges.light_midround.time_threshold = 18000
ruleset_ranges.heavy_midround.low = 0
ruleset_ranges.heavy_midround.high = 1
ruleset_ranges.heavy_midround.half_range_pop_threshold = 25
ruleset_ranges.heavy_midround.full_range_pop_threshold = 40
ruleset_ranges.heavy_midround.time_threshold = 36000
ruleset_ranges.latejoin.low = 1
ruleset_ranges.latejoin.high = 2
ruleset_ranges.latejoin.half_range_pop_threshold = 25
ruleset_ranges.latejoin.full_range_pop_threshold = 40
ruleset_ranges.latejoin.time_threshold = 0

[Medium-High Chaos]
name = "Medium-High Chaos"
min_pop = 0
advisory_report = "Advisory Level: <b>Black Orbit</b></center><BR>Your sector's advisory level is Black Orbit. Your sector's local communications network is currently undergoing a blackout, and we are therefore unable to accurately judge enemy movements within the region. However, information passed to us by GDI suggests a high amount of enemy activity in the sector, indicative of an impending attack. Remain on high alert and vigilant against any other potential threats."
ruleset_ranges.roundstart.low = 2
ruleset_ranges.roundstart.high = 3
ruleset_ranges.roundstart.half_range_pop_threshold = 25
ruleset_ranges.roundstart.full_range_pop_threshold = 40
ruleset_ranges.light_midround.low = 2
ruleset_ranges.light_midround.high = 3
ruleset_ranges.light_midround.half_range_pop_threshold = 25
ruleset_ranges.light_midround.full_range_pop_threshold = 40
ruleset_ranges.light_midround.time_threshold = 18000
ruleset_ranges.heavy_midround.low = 0
ruleset_ranges.heavy_midround.high = 2
ruleset_ranges.heavy_midround.half_range_pop_threshold = 25
ruleset_ranges.heavy_midround.full_range_pop_threshold = 40
ruleset_ranges.heavy_midround.time_threshold = 36000
ruleset_ranges.latejoin.low = 1
ruleset_ranges.latejoin.high = 3
ruleset_ranges.latejoin.half_range_pop_threshold = 25
ruleset_ranges.latejoin.full_range_pop_threshold = 40
ruleset_ranges.latejoin.time_threshold = 0

[High Chaos]
name = "High Chaos"
min_pop = 25
advisory_report = "Advisory Level: <b>Midnight Sun</b></center><BR>Your sector's advisory level is Midnight Sun. Credible information passed to us by GDI suggests that the Syndicate is preparing to mount a major concerted offensive on Nanotrasen assets in the Spinward Sector to cripple our foothold there. All stations should remain on high alert and prepared to defend themselves."
ruleset_ranges.roundstart.low = 3
ruleset_ranges.roundstart.high = 4
ruleset_ranges.roundstart.half_range_pop_threshold = 25
ruleset_ranges.roundstart.full_range_pop_threshold = 40
ruleset_ranges.light_midround.low = 1
ruleset_ranges.light_midround.high = 2
ruleset_ranges.light_midround.half_range_pop_threshold = 25
ruleset_ranges.light_midround.full_range_pop_threshold = 40
ruleset_ranges.light_midround.time_threshold = 12000
ruleset_ranges.heavy_midround.low = 1
ruleset_ranges.heavy_midround.high = 2
ruleset_ranges.heavy_midround.half_range_pop_threshold = 25
ruleset_ranges.heavy_midround.full_range_pop_threshold = 40
ruleset_ranges.heavy_midround.time_threshold = 18000
ruleset_ranges.latejoin.low = 2
ruleset_ranges.latejoin.high = 3
ruleset_ranges.latejoin.half_range_pop_threshold = 25
ruleset_ranges.latejoin.full_range_pop_threshold = 40
ruleset_ranges.latejoin.time_threshold = 0

[Roundstart Traitor]
weight = 10
min_pop = 0
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap.denominator = 38
repeatable_weight_decrease = 2
repeatable = 1
minimum_required_age = 0

[Roundstart Malfunctioning AI]
weight.1 = 0
weight.2 = 1
weight.3 = 3
weight.4 = 3
min_pop = 0
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap = 1
repeatable_weight_decrease = 2
repeatable = 1
minimum_required_age = 0

[Roundstart Blood Brothers]
weight = 5
min_pop = 0
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap.denominator = 29
repeatable_weight_decrease = 2
repeatable = 1
minimum_required_age = 0

[Roundstart Changeling]
weight = 3
min_pop = 0
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap.denominator = 29
repeatable_weight_decrease = 2
repeatable = 1
minimum_required_age = 0

[Roundstart Heretics]
weight = 3
min_pop = 0
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap.denominator = 24
repeatable_weight_decrease = 2
repeatable = 1
minimum_required_age = 0

[Roundstart Wizard]
weight.1 = 0
weight.2 = 0
weight.3 = 1
weight.4 = 2
min_pop = 0
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap = 1
repeatable_weight_decrease = 2
repeatable = 1
minimum_required_age = 0

[Roundstart Blood Cult]
weight.1 = 0
weight.2 = 1
weight.3 = 3
weight.4 = 3
min_pop = 0
blacklisted_roles = []
min_antag_cap.denominator = 20
min_antag_cap.offset = 1
# max_antag_cap = null ## defaults to min_antag_cap
repeatable_weight_decrease = 2
repeatable = 1
minimum_required_age = 0

[Roundstart Nukeops]
weight.1 = 0
weight.2 = 1
weight.3 = 3
weight.4 = 3
min_pop = 0
blacklisted_roles = []
min_antag_cap.denominator = 18
min_antag_cap.offset = 1
# max_antag_cap = null ## defaults to min_antag_cap
repeatable_weight_decrease = 2
repeatable = 1
minimum_required_age = 0

[Roundstart Clownops]
weight = 0
min_pop = 0
blacklisted_roles = []
min_antag_cap.denominator = 18
min_antag_cap.offset = 1
# max_antag_cap = null ## defaults to min_antag_cap
repeatable_weight_decrease = 2
repeatable = 1
minimum_required_age = 0

[Roundstart Revolution]
weight.1 = 0
weight.2 = 1
weight.3 = 3
weight.4 = 3
min_pop = 0
blacklisted_roles = []
min_antag_cap = 3
# max_antag_cap = null ## defaults to min_antag_cap
repeatable_weight_decrease = 2
repeatable = 1
minimum_required_age = 0

[Roundstart Spies]
weight.1 = 0
weight.2 = 1
weight.3 = 3
weight.4 = 3
min_pop = 0
blacklisted_roles = []
min_antag_cap.denominator = 20
min_antag_cap.offset = 1
# max_antag_cap = null ## defaults to min_antag_cap
repeatable_weight_decrease = 2
repeatable = 1
minimum_required_age = 0

[Extended]
weight = 0
min_pop = 0
blacklisted_roles = []
min_antag_cap = 0
# max_antag_cap = null ## defaults to min_antag_cap
repeatable_weight_decrease = 2
repeatable = 1
minimum_required_age = 0

[Meteor]
weight = 0
min_pop = 0
blacklisted_roles = []
min_antag_cap = 0
# max_antag_cap = null ## defaults to min_antag_cap
repeatable_weight_decrease = 2
repeatable = 1
minimum_required_age = 0

[Nations]
weight = 0
min_pop = 0
blacklisted_roles = []
min_antag_cap = 0
# max_antag_cap = null ## defaults to min_antag_cap
repeatable_weight_decrease = 2
repeatable = 1
minimum_required_age = 0

[Midround Wizard]
weight.1 = 0
weight.2 = 0
weight.3 = 1
weight.4 = 2
min_pop = 0
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap = 1
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Midround Nukeops]
weight.1 = 0
weight.2 = 1
weight.3 = 3
weight.4 = 3
min_pop = 0
blacklisted_roles = []
min_antag_cap.denominator = 18
min_antag_cap.offset = 1
# max_antag_cap = null ## defaults to min_antag_cap
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Midround Clownops]
weight = 0
min_pop = 0
blacklisted_roles = []
min_antag_cap.denominator = 18
min_antag_cap.offset = 1
# max_antag_cap = null ## defaults to min_antag_cap
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Blob]
weight.1 = 0
weight.2 = 1
weight.3 = 3
weight.4 = 3
min_pop.1 = 36
min_pop.2 = 30
min_pop.3 = 27
min_pop.4 = 25
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap = 1
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Xenomorph]
weight.1 = 0
weight.2 = 1
weight.3 = 5
weight.4 = 5
min_pop.1 = 36
min_pop.2 = 30
min_pop.3 = 27
min_pop.4 = 25
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap = 1
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Nightmare]
weight = 5
min_pop = 15
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap = 1
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Space Dragon]
weight.1 = 0
weight.2 = 3
weight.3 = 5
weight.4 = 5
min_pop.1 = 36
min_pop.2 = 30
min_pop.3 = 27
min_pop.4 = 25
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap = 1
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Abductors]
weight = 5
min_pop = 0
blacklisted_roles = []
min_antag_cap = 2
# max_antag_cap = null ## defaults to min_antag_cap
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Space Ninja]
weight.1 = 0
weight.2 = 0
weight.3 = 1
weight.4 = 2
min_pop.1 = 36
min_pop.2 = 30
min_pop.3 = 27
min_pop.4 = 25
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap = 1
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Spiders]
weight.1 = 0
weight.2 = 0
weight.3 = 1
weight.4 = 2
min_pop.1 = 36
min_pop.2 = 30
min_pop.3 = 27
min_pop.4 = 25
blacklisted_roles = []
min_antag_cap = 0
max_antag_cap = 2
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Revenant]
weight = 5
min_pop = 0
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap = 1
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Light Pirates]
weight = 3
min_pop = 0
blacklisted_roles = []
min_antag_cap = 0
# max_antag_cap = null ## defaults to min_antag_cap
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Heavy Pirates]
weight = 3
min_pop = 0
blacklisted_roles = []
min_antag_cap = 0
# max_antag_cap = null ## defaults to min_antag_cap
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Midround Changeling]
weight = 5
min_pop = 0
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap = 1
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Paradox Clone]
weight = 5
min_pop = 0
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap = 1
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Voidwalker]
weight = 5
min_pop = 0
blacklisted_roles = []
min_antag_cap = 1
max_antag_cap = 1
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Midround Traitor]
weight = 10
min_pop = 0
blacklisted_roles = []
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Midround Malfunctioning AI]
weight.1 = 0
weight.2 = 1
weight.3 = 3
weight.4 = 3
min_pop = 0
blacklisted_roles = []
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Midround Blob]
weight.1 = 0
weight.2 = 1
weight.3 = 3
weight.4 = 3
min_pop = 0
blacklisted_roles = []
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Midround Obsessed]
weight.1 = 5
weight.2 = 5
weight.3 = 3
weight.4 = 1
min_pop = 0
blacklisted_roles = []
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Latejoin Traitor]
weight = 10
min_pop = 0
blacklisted_roles = []
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Latejoin Heretic]
weight = 3
min_pop = 0
blacklisted_roles = []
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Latejoin Changeling]
weight = 3
min_pop = 0
blacklisted_roles = []
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0

[Latejoin Revolution]
weight = 1
min_pop = 0
blacklisted_roles = []
repeatable_weight_decrease = 2
repeatable = 0
minimum_required_age = 0


