# This reusable workflow is a wrapper around `actions/setup-node`, to use the version specified in
# `dependencies.sh`.
name: Setup Node
description: Install Node using the version specified in `dependencies.sh`; additionally, restores the Yarn cache if one exists

inputs:
  restore-yarn-cache:
    description: 'Whether to restore the Yarn cache alongside installing node.'
    required: false
    type: boolean

runs:
  using: composite
  steps:
    - name: Configure Node version
      shell: bash
      run: |
        source dependencies.sh
        echo "NODE_VERSION_REQUIRED=$NODE_VERSION_LTS" >> $GITHUB_ENV
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION_REQUIRED }}
        cache: ${{ inputs.restore-yarn-cache && 'yarn' || '' }}
        cache-dependency-path: ${{ inputs.restore-yarn-cache && 'tgui/yarn.lock' || '' }}
