name: "Autostaled PR Notification"
on:
  pull_request_target:
    types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == "Stale" }}
    steps:
      - name: "Check for DISCORD_WEBHOOK"
        id: secrets_set
        env:
          ENABLER_SECRET: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          unset SECRET_EXISTS
          if [ -n "$ENABLER_SECRET" ]; then SECRET_EXISTS=true ; fi
          echo "SECRETS_ENABLED=$SECRET_EXISTS" >> $GITHUB_OUTPUT
      - name: Send Discord notification
        uses: tgstation/discord-notify@v3
        if: >
          steps.secrets_set.outputs.SECRETS_ENABLE
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: ${{ github.event.pull_request.user.login }} - ${{ github.event.pull_request.title }}
          message: "**Pull Request #${{ github.event.pull_request.number }} automatically marked as stale.**"
          include_image: false
          show_author: false
          avatar_url: https://avatars.githubusercontent.com/u/1363778?s=200&v=4
          username: GitHub
          title_url: "${{ github.event.pull_request.html_url }}"
